### ISSUE TITLE
Publish tokio-service

### ISSUE THREAD

**Issue by hanscj1** [tokio-rs/tokio-service#10]
Not sure of the long-term plans but it would be nice if this project was published as a crate.

**Comment by carllerche** [comment]
Hopefully in a week or so! We are just waiting to coordinate with tokio-proto.

**Comment by wshatch** [comment]
What needs to be done for 0.1 to be published?

**Comment by sateffen** [comment]
Now it's [published](https://crates.io/crates/tokio-service), so I guess this issue can be closed :)
