### ISSUE TITLE
Connection state

### ISSUE THREAD

**Issue by anton-dutov** [tokio-rs/tokio-service#25]
By example, some rpc service with persistent connections, typical work is 
1. Connect
2. Auth
3. Quering...

At step two we created auth token and bound to socket (all socket's have bounded HashMap, where state saves), how to  impl that via Service?

**Comment by carllerche** [comment]
The rule of thumb is that anything that is socket specific should not be at the `Service` layer (there are, of course, exceptions). It can be done at the transport layer, which is per socket: https://tokio.rs/docs/going-deeper-tokio/transports/.

That said, it can also be possible to do at the `Service` layer once `NewService` returns a future:

```rust
impl NewService for MyService {
    fn new_service(&self) -> Self::Future {
        let token = self.token.clone();
        self.proto.new_service()
            .and_then(|s| s.call(Auth(token))
            .and_then(|resp| {
                validate_resp(resp)?
                // return authenticated service
            })
    }
}
```

**Comment by anton-dutov** [comment]
So, where are save state between requests?

**Comment by carllerche** [comment]
If you want to save state between requests, you should use an `Rc` or `Arc` somewhere. The "somewhere" depends on the details of what you want the state to be shared across.

**Comment by anton-dutov** [comment]
How to get connection token (e.g. socket handle) within Service? (for creating state hashmap)
