### ISSUE TITLE
Add Filter abstraction

### ISSUE THREAD

**Issue by DustinByfuglien** [tokio-rs/tokio-service#28]
I think adding a [Filter](https://twitter.github.io/finagle/guide/ServicesAndFilters.html) abstraction may be useful.

**Comment by carllerche** [comment]
@DustinByfuglien I would suggest that you file issues in [Tower](github.com/tokio-rs/tower). This will be the next iteration of the `Service` abstraction.

That said, we aren't going to be calling it "Filter", instead we will call it "Middleware" as that is more descriptive I think. https://github.com/tokio-rs/tokio-service/pull/21 offers a proposal.

**Comment by DustinByfuglien** [comment]
Thanks. I'll looking into
