### ISSUE TITLE
tokio-service vs. tower?

### ISSUE THREAD

**Issue by flosse** [tokio-rs/tokio-service#29]
At the moment I can't see a clear direction of `tokio-service` and `tokio-proto`. Some people talk about `tower` [to be the replacement of `tokio-service`](https://github.com/tokio-rs/tokio-proto/issues/202#issuecomment-361092210) (I'd disagree) and there are statements like [these](https://github.com/tokio-rs/tokio-proto/issues/202#issuecomment-368602692):
>Tower is going to be the replacement for `tokio-service`.

I'm a bit confused now.
I really don't care about naming but if all the crates do the same we should synergize the power into **one** crate. If they are different we should **precisely define the differences**.
So would you mind to help out to clear up the situation?

**Comment by carllerche** [comment]
tokio-service is going to be deprecated once tower is released. Tokio will focus on the async I/O runtime aspects (reactor, executor, timer, etc...) and Tower will focus on the request / response abstraction.

It's mostly about having each project focus on one thing.

**Comment by flosse** [comment]
> tower-service is going to be deprecated once tower is released.

I see, that's good to know :)
So the future of `tokio-proto` is still unclear but that's not part of this issue ;-)

**Comment by flosse** [comment]
> tower-service is going to be [..]

You're talking about `tokio-service`, don't you?

**Comment by carllerche** [comment]
@flosse yes! thanks (i updated the comment).
